### DISCUSSION TITLE
WT32-ETH01 Compatibility

### DISCUSSION THREAD

**Discussion by sanjay900** [Kaldek/rat-ratgdo#93] [General]
Figured i would note that these do work - i had an easily accessible ethernet port near my GDO and was having issues with wifi dropouts, the only thing to note is that there really aren't many pins on these, so i ended up disabling all the dry contact stuff.

I ended up using these pins - others may work although this board is a bit weird with its strapping pins
  ```
  uart_tx_pin: GPIO32 # CFG
  uart_rx_pin: GPIO14 
  input_obst_pin: GPIO4
  ```
  
 You do end up needing to put your own YAML together anyways since you need to get rid of the improv serial stuff and swap wifi out for ethernet. I ended up with the following config:

```
substitutions:
  name: ratgdov25-b92cd8
  friendly_name: RATGDOv2.5 Sanjay's Garage - eth
  id_prefix: ratgdov2
  uart_tx_pin: GPIO32 # CFG
  uart_rx_pin: GPIO14 
  input_obst_pin: GPIO4

external_components:
  - source:
      type: git
      url: https://github.com/ratgdo/esphome-ratgdo
    refresh: 1s

web_server:

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ratgdo.esphome
    version: "2.0"

esp32:
  board: esp-wrover-kit

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

ota:

logger:
    level: DEBUG

api:
  id: api_server
  encryption:
    key: xx
  
  services:
  - service: wipe_devices_from_gdo_memory
    variables:
      devices_to_wipe: string
    then:
      - lambda: !lambda |-
          if(devices_to_wipe.compare("all") == 0) {
            id($id_prefix).clear_paired_devices(ratgdo::PairedDevice::ALL);
          } else if (devices_to_wipe.compare("remote") == 0) {
            id($id_prefix).clear_paired_devices(ratgdo::PairedDevice::REMOTE);
          } else if (devices_to_wipe.compare("keypad") == 0) {
            id($id_prefix).clear_paired_devices(ratgdo::PairedDevice::KEYPAD);
          } else if (devices_to_wipe.compare("wall") == 0)  {
            id($id_prefix).clear_paired_devices(ratgdo::PairedDevice::WALL_CONTROL);
          } else if (devices_to_wipe.compare("accessory")  == 0) {
            id($id_prefix).clear_paired_devices(ratgdo::PairedDevice::ACCESSORY);
          }

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

preferences:
  flash_write_interval: 1min

ratgdo:
  id: ${id_prefix}
  input_gdo_pin: ${uart_rx_pin}
  output_gdo_pin: ${uart_tx_pin}
  input_obst_pin: ${input_obst_pin}
  on_sync_failed:
    then:
      - homeassistant.service:
          service: persistent_notification.create
          data:
            title: "${friendly_name} sync failed"
            message: "Failed to communicate with garage opener on startup."
            notification_id: "esphome_ratgdo_${id_prefix}_sync_failed"

sensor:
  - platform: ratgdo
    id: ${id_prefix}_openings
    type: openings
    entity_category: diagnostic
    ratgdo_id: ${id_prefix}
    name: "Openings"
    unit_of_measurement: "openings"
    icon: mdi:open-in-app
  - platform: ratgdo
    id: ${id_prefix}_paired_devices_total
    type: paired_devices_total
    entity_category: diagnostic
    ratgdo_id: ${id_prefix}
    name: "Paired Devices"
    icon: mdi:remote

lock:
  - platform: ratgdo
    id: ${id_prefix}_lock_remotes
    ratgdo_id: ${id_prefix}
    name: "Lock remotes"

switch:
  - platform: ratgdo
    id: "${id_prefix}_learn"
    type: learn
    ratgdo_id: ${id_prefix}
    name: "Learn"
    icon: mdi:plus-box
    entity_category: config

binary_sensor:
  - platform: ratgdo
    type: motion
    id: ${id_prefix}_motion
    ratgdo_id: ${id_prefix}
    name: "Motion"
    device_class: motion
  - platform: ratgdo
    type: obstruction
    id: ${id_prefix}_obstruction
    ratgdo_id: ${id_prefix}
    name: "Obstruction"
    device_class: problem
  - platform: ratgdo
    type: button
    id: ${id_prefix}_button
    ratgdo_id: ${id_prefix}
    name: "Button"
    entity_category: diagnostic
  - platform: ratgdo
    type: motor
    id: ${id_prefix}_motor
    ratgdo_id: ${id_prefix}
    name: "Motor"
    device_class: running
    entity_category: diagnostic

number:
  - platform: ratgdo
    id: ${id_prefix}_rolling_code_counter
    type: rolling_code_counter
    entity_category: config
    ratgdo_id: ${id_prefix}
    name: "Rolling code counter"
    mode: box
    unit_of_measurement: "codes"

  - platform: ratgdo
    id: ${id_prefix}_opening_duration
    type: opening_duration
    entity_category: config
    ratgdo_id: ${id_prefix}
    name: "Opening duration"
    unit_of_measurement: "s"

  - platform: ratgdo
    id: ${id_prefix}_closing_duration
    type: closing_duration
    entity_category: config
    ratgdo_id: ${id_prefix}
    name: "Closing duration"
    unit_of_measurement: "s"

  - platform: ratgdo
    id: ${id_prefix}_client_id
    type: client_id
    entity_category: config
    ratgdo_id: ${id_prefix}
    name: "Client ID"
    mode: box

cover:
  - platform: ratgdo
    id: ${id_prefix}_garage_door
    device_class: garage
    name: "Door"
    ratgdo_id: ${id_prefix}

light:
  - platform: ratgdo
    id: ${id_prefix}_light
    name: "Light"
    ratgdo_id: ${id_prefix}

button:
  - platform: restart
    id: ${id_prefix}_restart
    name: "Restart"
  - platform: safe_mode
    id: ${id_prefix}_safe_mode
    name: "Safe mode boot"
    entity_category: diagnostic

  - platform: template
    id: ${id_prefix}_query_status
    entity_category: diagnostic
    name: "Query status"
    on_press:
      then:
        lambda: !lambda |-
          id($id_prefix).query_status();

  - platform: template
    id: ${id_prefix}_query_openings
    name: "Query openings"
    entity_category: diagnostic
    on_press:
      then:
        lambda: !lambda |-
          id($id_prefix).query_openings();

  - platform: template
    id: ${id_prefix}_sync
    name: "Sync"
    entity_category: diagnostic
    on_press:
      then:
        lambda: !lambda |-
          id($id_prefix).sync();

  - platform: template
    id: ${id_prefix}_toggle_door
    name: "Toggle door"
    on_press:
      then:
        lambda: !lambda |-
          id($id_prefix).door_toggle();
```

**Comment by youaintnobody** [comment]
Hey mate, is there enough pins at all for?
```typescript
  dry_contact_open_pin: D5
  dry_contact_close_pin: D6
  dry_contact_light_pin: D3
``` 

I noticed there's no USB on this device, do you flash it with a [CH340G USB to TTL Serial Wire Adapter](https://temperosystems.com.au/products/ch340g-usb-to-ttl-serial-wire-adapter/)?

**Comment by sanjay900** [comment]
I flashed it with a random aliexpress TTL adapter i had lying around. There probably would be enough pins, i just was having trouble with my transistors so i kept disabling things until i realised where the problem was

**Comment by wirecuttr** [comment]
Thanks for this. So without the dry contacts you're just using it as a sensor with any control functions, correct?

**Comment by sanjay900** [comment]
My garage door has a seperate pin for security+, so my wall button still goes directly to the garage and I can then use security+ to control the garage door from home assistant

**Comment by wirecuttr** [comment]
> My garage door has a seperate pin for security+, so my wall button still goes directly to the garage and I can then use security+ to control the garage door from home assistant

Got it. Thanks!

**Comment by edwork** [comment]
Something changed in the ratgdo main branch, I had to pin the external source to a commit from around the time of this post - like this:  

```
external_components:
  - source:
      type: git
      url: https://github.com/ratgdo/esphome-ratgdo
      ref: 17a74f8a298cafbd7f82aab4fb34e16549cd9bc3
    refresh: 1s
```

Otherwise ESPHome failed to build the image.

**Comment by transplier** [comment]
Made a unit with this board yesterday and would like to add some notes:

I used the following pin config:
```yaml
  uart_tx_pin: GPIO14 # "red wire" TX
  uart_rx_pin: GPIO35 # "red wire" RX
  input_obst_pin: GPIO36 # Obstruction input

  status_door_pin: GPIO5
  status_obstruction_pin: GPIO4

  dry_contact_open_pin: GPIO20 # Dummy, not used.
  dry_contact_close_pin: GPIO19 # Dummy, not used.
  dry_contact_light_pin: GPIO21 # Dummy, not used.
```

The dummy dry contact pins are a terrible hack (I just chose pins that seem unused). I have concerns that they may be floating and trigger unexpectedly. I am waiting for https://github.com/ratgdo/esphome-ratgdo/issues/264 to be fixed. I had an issue where the gdo would open every time the ratgdo rebooted, which I traced to the dummy GPIO pin I was using always showing a button press. I papered over it by trying other pins until I found one that returned an appropriate status, but it's far from a permanent solution.

I ended up needing to add a 10k pullup on GPIO35 to make sensor status update properly. I suppose an internal pullup should have been used, but I haven't dug into why that isn't working on this board. Probably some aspect of that specific GPIO pin. Without the pullup, I could successfully toggle the door open and closed, but that's pretty much it.

Paul, if you're reading this, consider making a wired version. I'm not sure what your stance is on this 3rd-party reverse engineering project (there seems to be no discussion of it on the official repos), but if there were a wired option from you I probably would have bought it. I dislike wifi for critical applications, such as gaining entry to my home. If WiFi drops, I might have no way to get in (only if I forget my keys, but misfortune tends to happen in clumps, doesn't it?).
