### ISSUE TITLE
Only able to open and close door

### ISSUE THREAD

**Issue by dig12345** [Kaldek/rat-ratgdo#109]
Hi, I built the ESP32 board using [this schematic ](https://github.com/Kaldek/rat-ratgdo/blob/main/schematics/ratgdo%20open%20source%20ESP-32_schem_v6.png) and connected it to a Esp32 using the GPIO pins for ESp32 . Flashed 2.0 firmware per the readme. I am able to toggle the door open and closed which is cool but I'm not receiving any data about state of the door etc. I checked wiring far as I can tell everything is correct. I'm also unable to toggle the light or remote lock. I am getting obstruction sensor status correctly. Any ideas?

Thanks

**Comment by audioeptesicus** [comment]
I just built mine too, using an ESP32 board like yourself, following the schematic and and flashing with the 2.0 firmware.

I can trigger door up, door down, the lights, but I can't stop the door or read the position.

With the door opened, pressing the close button:
```
10:15:48 | [D] | [cover:076] | 'Door' - Setting
10:15:48 | [D] | [cover:084] | Position: 0%
10:15:48 | [D] | [number:012] | 'Rolling code counter': Sending state 445.000000
10:15:50 | [D] | [ratgdo:221] | Motor: state=ON
```

While the door is closing, I press the stop button and it reports that the door is not moving:
```
10:15:51 | [D] | [cover:076] | 'Door' - Setting
10:15:51 | [D] | [cover:080] | Command: STOP
10:15:51 | [W] | [ratgdo:484] | The door is not moving.
```

Here's my ESPHome .yaml:
```
substitutions:
  id_prefix: garagedoor
  friendly_name: "GarageDoor"
  uart_tx_pin: D4
  uart_rx_pin: D2
  input_obst_pin: D7
  status_door_pin: D0
  status_obstruction_pin: D8
  dry_contact_open_pin: D5
  dry_contact_close_pin: D6
  dry_contact_light_pin: D3

web_server:

esphome:
  name: ${id_prefix}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ratgdo.esphome
    version: "2.0"

esp32:
  board: wemos_d1_mini32

dashboard_import:
  package_import_url: github://ratgdo/esphome-ratgdo/v2board_esp32_d1_mini.yaml@main

packages:
  remote_package:
    url: https://github.com/ratgdo/esphome-ratgdo
    files: [base.yaml]
    refresh: 1s

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

# Enable logging
logger:

improv_serial:

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxxxxxxx"

ota:
  - platform: esphome
    password: "xxxxxxxxxxxxxxxx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 10.0.120.121
    gateway: 10.0.120.1
    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Garagedoor Fallback Hotspot"
    password: "xxxxxxxxxxxxxxxx"

captive_portal:
```

Any thoughts here?
