### ISSUE TITLE
Unable to send commands, but can receive status OK [solved]

### ISSUE THREAD

**Issue by sillyfrog** [Kaldek/rat-ratgdo#125]
I built the circuit as per the README.md (using a 2N7002 and AO3400, with a [Lolin D1 Mini ESP8266](https://www.wemos.cc/en/latest/d1/d1_mini.html)), and found I was able to receive signals (light on/off, open/closed) after a a few open/closes of the door, but I could never send a command.

After reading and looking around, changing parts etc (eg: swapping MOSFETS), I eventually found this circuit worked perfectly for me: https://github.com/Kaldek/rat-ratgdo/blob/main/kicad_files/D1%20Mini%20-%20ESP8266/RatGDO-OpenSource-D1Mini-ESP8266.pdf

This was connecting to a _Commander Ultimate MJ3800MYQ_. With the `RED/CTRL` connected to the Commander pin 1 (green), `BLK/OBST` to Commander pin 5 (grey) and ground to Commander pin 3 (white).

I'm not sure if I should put this up as a discussion, or put in a suggested PR to make the change to the home page as this circuit appears more reliable (at least for me), but wanted to post in case it's of value to others.

For all this testing, this was my ESPHome configuration (this is what I ended up with, and didn't change too much along the way):

```yaml
substitutions:
  id_prefix: garage2025
  friendly_name: "Garage Door"
  uart_tx_pin: D1
  uart_rx_pin: D2
  input_obst_pin: D7
  status_door_pin: D0
  status_obstruction_pin: D8
  dry_contact_open_pin: D5
  dry_contact_close_pin: D6
  dry_contact_light_pin: D3

web_server:

esphome:
  name: ${id_prefix}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ratgdo.esphome
    version: "2.5"

esp8266:
  board: d1_mini
  restore_from_flash: true

# dashboard_import:
#   package_import_url: github://ratgdo/esphome-ratgdo/v25board_esp8266_d1_mini_lite.yaml@main

packages:
  remote_package:
    url: https://github.com/ratgdo/esphome-ratgdo
    files: [base.yaml]
    refresh: 1s

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

api:
  id: api_server

improv_serial:

wifi:
...

logger:

```
