### ISSUE TITLE
8266 nodemcu help

### ISSUE THREAD

**Issue by nodiaque** [Kaldek/rat-ratgdo#37]
Hello everyone,

I got some nodemcu 8266 laying around and I wanted to try this project. While I see it's for the D1 mini, I still flashed both 2.0 and 2.5 version of the 8266 and the flashing work, I also got the gui working. Now, the log are flooded with collision which I guess is because it's not using the right gpio. Right now, nothing is connected to it, it's just flashed and that's it.

My nodemcu have a green board and while flashing both 2.0 and 2.5, what I notice is with 2.0 I have 2 led one on the board while with 2.5 I only have one.

Outside of that, per basic, what GPIO are needed for what (outside of nodemcu I just mean generic)? And if I want to reassign to be useable on my nodemcu, how do I go about changing that?

Thank you

**Comment by rlowens** [comment]
> I see it's for the D1 mini

Any ESP8266 or ESP32 will work, this is just the example.

> the log are flooded with collision

Expected behavior if you don't have it connected to a Garage Door Opener.

> with 2.0 I have 2 led one on the board while with 2.5 I only have one.

The ratgdo v2.0 uses pin D4/GPIO2 for TX and the ratgdo v2.5 switched to using pin D1/GPIO5 for TX. The blue LED on the ESP8266 module is on GPIO2. We recommend matching the ratgdo v2.5 pins, but many pins would work if you customize the firmware.

> what GPIO are needed for what

For connecting to the GDO:
D1/GPIO5 uart_tx_pin
D2/GPIO4 uart_rx_pin
D7/GPIO13 input_obst_pin

If you want to use optional inputs for toggle switches:
D5/GPIO15 dry_contact_open_pin
D6/GPIO12 dry_contact_close_pin
D3/GPIO0 dry_contact_light_pin
And the optional binary outputs are:
D0/GPIO16 status_door_pin
D8/GPIO15 status_obstruction_pin

> And if I want to reassign to be useable on my nodemcu, how do I go about changing that?

You load the ESPHome firmware, adopt it into the ESPHome Addon, then edit the device .yaml there to change the settings you want. Since it loads the defaults from a package, you can overwrite those settings by defining them in the device .yaml.

It will load the defaults from https://github.com/ratgdo/esphome-ratgdo/blob/main/static/v25board_esp8266_d1_mini_lite.yaml

And you will start with a device .yaml looking something like this:
```
substitutions:
  name: ratgdov2-11999c
  friendly_name: ratgdo
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25board_esp8266_d1_mini_lite.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: iWx8HgETC
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

Which you might want to change to something like:
```
substitutions:
  name: ratgdov2-11999c
  friendly_name: Garage Door Opener
  uart_tx_pin: GPIO5
  uart_rx_pin: GPIO4
  input_obst_pin: GPIO13
  status_door_pin: GPIO16
  status_obstruction_pin: GPIO15
  dry_contact_open_pin: GPIO15
  dry_contact_close_pin: GPIO12
  dry_contact_light_pin: GPIO0
esp8266:
  board: nodemcuv2
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25board_esp8266_d1_mini_lite.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: iWx8HgETC
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
web_server:
  auth:
    username: !secret web_username
    password: !secret web_password
```
